### ISSUE TITLE
Node renaming

### ISSUE THREAD

**Issue by gaitat** [mikolalysenko/strongly-connected-components#3]
I noticed that the nodes get renamed (reshuffled) after the execution of the algorithm. Is that necessary?

**Comment by mikolalysenko** [comment]
It shouldn't be doing that.  Can you post an example?

**Comment by gaitat** [comment]
My example is: adjacencyList = [ [2], [0], [], [1,6], [3], [3], [] ] which after running SCC on it returns adjacencyList = [ [], [0], [1], [], [2,3], [4], [4] ] which if you draw it out does have the same structure as the original but the vertices are all renamed.

**Comment by jaspervdg** [comment]
In principle (assuming you're saying that `scc([ [2], [0], [], [1,6], [3], [3], [] ]).adjacencyList` equals `[ [], [0], [1], [], [2,3], [4], [4] ]`), this is expected behaviour (and in our original use case, extremely useful). The point is that the adjacency list it returns is the adjacency list of the strongly connected components, and that the strongly connected components are topologically sorted.

In your particular case the graph is acyclic, so each vertex is a strongly connected component and the algorithm boils down to doing a topological sort. The `components` property that is returned allows you to figure out what SCC maps to which original vertices (or in your case, original vertex).

If the algorithm would not do a topological sort (which is done implicitly btw.: it's not an extra step, just a consequence of the algorithm used), then in your example it would effectively do nothing. I thus assume that in general you are in fact interested in finding SCCs in graphs with cyles. However, in that case there is no obvious "correct" order of the SCCs (since there is no longer a one-on-one mapping between SCCs and vertices in the original graph), and the topological order is often quite useful. Did you have anything specific in mind as an alternative?

**Comment by gaitat** [comment]
I didn't realize that topological sorting is a byproduct of Tarjan's algorithm. But I still fail to see how the `components` property allows me to figure out the mapping between the original vertices and the topological sorted ones. 

Thank you.

**Comment by mikolalysenko** [comment]
Ah, I see what you mean here.  I think you are confused about the nature of the algorithm.  It gives a partition of the nodes into strongly connected components with a condensation (that is edges between the components).  The nodes in the condensation (which are the strongly connected components) bear no relation to the nodes in the original graph, nor should you try to think of them as such.

The order of the original nodes though are still preserved by the result.components arrays which tell you which vertices are contained in which component.

In this case, the module is currently working as intended and no fix is necessary.
